Add information about credentials
sebask/dsm-vagrant-box pull request #1
Opened 2019-02-19 23:11 UTC by aivus

2019-02-24 07:57 UTC, sebask requested changes

2019-02-24 07:57 UTC, sebask commented on README.md
> +Login: vagrant
```suggestion
Username: `vagrant`
```

2019-02-24 07:57 UTC, sebask commented on README.md
> +**Credentials:**
```suggestion
**Credentials preconfigured Vagrant user:**
```

2019-02-24 07:57 UTC, sebask commented on README.md
> +
```suggestion
```

2019-02-24 07:57 UTC, sebask commented on README.md
> +Password: vagrant
```suggestion
Password: `vagrant`
```

2019-02-25 08:57 UTC, aivus commented
@sebask done

2019-02-25 21:39 UTC, sebask approved these changes

2019-02-25 21:39 UTC, merged